### ISSUE TITLE
Rsense fails on startup

### ISSUE THREAD

**Issue by stevenheidel** [Samsinite/rsense#1]
no .rsense file detected, creating .rsense file
/bin/sh: cannot create /home/steven/.rvm/gems/ruby-1.9.2-head/gems/redcar-0.3.8.1/plugins/rsense/.rsense: Directory nonexistent

**Comment by Samsinite** [comment]
This should be fixed now, rsense was expecting the plugin to be in redcar/plugins instead of ~/.redcar/plugins
Let me know if you still have problems.

-Sam

**Comment by stevenheidel** [comment]
Thanks, works great now.
